
<script type="text/javascript" src="<?php echo BASE_URL;?>ckeditor/ckeditor.js"></script>
<div class="container">
    <div class="container">
        <h4>Add Posts <a href="post-list" class="btn btn-info btn-small">View Posts</a></h4>

        <table class="table">
            <form method="post" enctype="multipart/form-data" action="add-post">
                <tr>
                    <td class="span2">Title:</td>
                    <td class="span8"><input type="text" name="post_title" required/></td>

                </tr>
                <tr>
                    <td class="span2">Type:</td>
                    <td class="span8">
                        <select name="post_type">
                            <option value="post">Post</option>
                            <option value="news">News & Events</option>
                            <option value="facilites">Facilities</option>
                            
                        </select> 
                    </td>

                </tr>
                <tr>
                    <td class="span2">Image:</td>
                    <td class="span8">
                        <input type="file" name="post_image"/>

                    </td>
                </tr>
                <tr>
                    <td class="span2">Body:</td>
                    <td class="span8"><textarea id="post_body" name="post_body"></textarea></td>
                </tr>
                <tr>
                    <td>Publish:</td>
                    <td>
                        <label class="radio inline">Yes</label>
                        <input type="radio" class="radio" name="active" checked value="Yes"/>
                        <label class="radio inline">No</label>
                        <input type="radio" class="radio" name="active" value="No"/>

                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Add Post" name="submit" class="btn btn-inverse"/></td>
                </tr>
            </form>    
        </table>

    </div>
</div>

<script type="text/javascript">
    CKEDITOR.replace('post_body');
</script>