<h4>Change Password</h4>
<hr>
<div class="table-form box-border">
    <table>
        <?php ?>
        <form method="post" action="<?php echo BASE_URL;?>admin/user/change-password">
            <tr>
                <td>Old Password:</td>
                <td><input type="password" name="old_password" required/></td>
            </tr>
            <tr>
                <td>New Password:</td>
                <td><input type="password" name="new_password" required/></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" name="submit" value="Change Password"/></td>
            </tr>
        </form>


    </table>
</div>