<?php $session = new Zend_Session_Namespace('Zend_Auth'); //Zend_Auth uses Zend_Session_Namespace for storage ?>
<a href="<?php echo BASE_URL.'admin/index/logout'?>" class="btn btn-danger">Log Out</a>
<div id='content'>
    <a href='<?php
    echo $this->url(array(
        'controller' => 'user',
        'action' => 'user-list',
    ));
    ;
    ?>'>
        <div class='section'>
            <h4>User Management</h4> 
            <img src="<?php echo BASE_URL; ?>img/user_mgmt.jpeg" width="100px" height="100px" class="box-border"/>

        </div>
    </a>
    <a href='<?php
    echo $this->url(array(
        'controller' => 'gallery',
        'action' => 'album-list',
        'userId' => $session->Id
    ));
    ?>'>
        <div class='section'>
            <h4>Gallery Management</h4> 
            <img src="<?php echo BASE_URL; ?>img/images.jpeg" width="100px" height="100px"class="box-border"/>
        </div>
    </a>
    <a href='<?php
    echo $this->url(array(
        'controller' => 'content-management',
        'action' => 'post-list',
        'userId' => $session->Id
    ));
    ?>'>
        <div class='section'>
            <h4>Content Management</h4> 
            <img src="<?php echo BASE_URL; ?>img/cms.jpeg" width="100px" height="100px"class="box-border"/>
        </div>
    </a>
</div>
<div class='clearfix'></div>