<?php
$post = new Default_Model_Post();
$newsInfo = $this->newsInfo;
$facilities=$this->facilitiesSidebar;
$contact=$this->contact;
$academic=$this->academicSidebar;
?>
<title>News & Events</title>
<div class="row-fluid">
    <div id='main_container' class="span12">
        <h1 class="page-head">News & Events</h1>
        <div id="container" class="span8">
            <div class="news-body"  >
                
                <hr>
                <?php
                $i = 1;
                foreach ($newsInfo as $value):
                    ?>

                    <div  id="first" class="news-title">

                        <h5><?php echo $value['post_title'] ?>
                            <input type="button" value="Show" id="show-<?php echo $i; ?>" class="btn-show btn btn-small pull-right" onclick="changeContent(<?php echo $i; ?>);"><br/>
                            <input type="button" value="Hide" id="btn-<?php echo $i; ?>" class="btn-hide btn btn-small btn-inverse" onclick="loadNull(<?php echo $i; ?>);">
                        </h5>
                        <hr>

                        <span id="lessPara-<?php echo $i; ?>">
                            <?php
                            $snip = $post->word_limiter($value['post_body'], 30);
                            echo '<p>' . $snip . '...</p>';
                            ?>
                        </span>

                        <span id="<?php echo $i; ?>"  >
                            <div class="news-content">
                                <?php echo $value['post_body']; ?>
                            </div>
                            <hr>
                        </span>



                    </div>

                    <?php
                    $i++;
                endforeach;
                ?>

            </div>
        </div>
        <div class='recent_news_event '>
            <div class="span4">
                <div class="accordion " id="accordion2">
                    <div class="accordion-group">
                        <div class="accordion-heading accordian-head ">
                            <a class="accordion-toggle accordion-style" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                                <h6>Facilities <i class="icon-plus-sign pull-right"></i></h6>
                            </a>
                        </div>
                        <div id="collapseOne" class="accordion-body collapse in">
                            <div class="accordion-inner">
                                <?php
                                if (!empty($facilities)):
                                    $count = count($facilities);
                                    $i = 0;
                                    foreach ($facilities as $value):
                                        ?>
                                        <li>
                                            <a href="<?php echo BASE_URL; ?>facilities/facility/id/<?php echo $value['id']; ?>"><?php echo $value['post_title']; ?></a>
                                            <?php
                                            if ($i + 1 === $count):
                                                ?>
                                                <a href="<?php echo BASE_URL; ?>facilities" class="more-info pull-right">More &raquo;</a>
                                            <?php endif; ?>
                                        </li>
                                        <?php
                                        $i++;
                                    endforeach;
                                endif;
                                ?>
                            </div>
                        </div>
                    </div>

                    <div class="accordion-group">
                        <div class="accordion-heading accordian-head">
                            <a class="accordion-toggle event-head" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                                <h6>Our Mission<i class="icon-plus-sign pull-right"></i></h6>
                            </a>
                        </div>
                        <div id="collapseTwo" class="accordion-body collapse">
                            <div class="accordion-inner">

                                <li>A passion for excellence</li>
                                <li>Compassionate commitment </li>
                                <li>Innovative Spirit </li>
                                <li>Ability to accept risks and challenges </li>
                                <li>Competence </li>
                                <li>Creativity  </li>


                            </div>
                        </div>
                    </div>


                    <div class="accordion-group">
                        <div class="accordion-heading accordian-head">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
                                <h6>Academic <i class="icon-plus-sign pull-right"></i></h6>
                            </a>
                        </div>
                        <div id="collapseThree" class="accordion-body collapse">
                            <div class="accordion-inner">
                                <?php
                                if (!empty($academic)):
                                    $count = count($academic);
                                    $i = 0;
                                    foreach ($academic as $value):
                                        ?>
                                        <li>
                                            <a href="<?php echo BASE_URL; ?>academic/academic-post/id/<?php echo $value['id']; ?>" class=""><?php echo $value['post_title']; ?></a>
                                            <?php if ($i + 1 === $count): ?>
                                                <a href='<?php echo BASE_URL; ?>academic' class='more-info pull-right'>More &raquo;</a>
                                            <?php endif; ?>
                                        </li>
                                        <?php
                                        $i++;
                                    endforeach;
                                endif;
                                ?>
                            </div>
                        </div>
                    </div>


                </div>
                <div>
                    <?php
                    if (!empty($contact)):
                        foreach ($contact as $value):
                            ?>
                            <h5><?php echo $value['post_title']; ?></h5>
                            <hr>
                            <div id="contact-info">
                                <?php echo $value['post_body']; ?>
                            </div>

                            <?php
                        endforeach;
                    endif;
                    ?>
                </div>  
            </div>




        </div>
    </div>
</div>
<script type="text/javascript">
                $(document).ready(function() {
                    loadInitial();
                });
</script>