<h4>Albums</h4>
<hr>

<div id="view-content" style="margin: 50px 100px 0px 100px;">
    <table class="table table-striped table-bordered">
        <tr class="success">
            <td>
                s.no
            </td>
            <td>
                name
            </td>
            <td>
                Published
            </td>
            <td>
                <a href='<?php echo BASE_URL; ?>admin/gallery/add-album/' class="btn  btn-inverse">Add Album</a>
            </td>
        </tr>
    <?php
        $albumlist = $this->albumlist;
        $checkval=false;
        $counter=1;
        if(count($albumlist)>0)
        {
            foreach ($albumlist as  $value) {
                if($checkval)
                {
                    echo '</tr>';
                    echo '<tr>';
                    
                }?>
            <td>
                <?php echo $counter;?>
            </td>
            <td>
                <?php echo $value['album_name'];?>
            </td>
            <td>
                <?php echo 'yes';?>
            </td>
            <td>
                <a href="<?php echo BASE_URL; ?>admin/gallery/edit-album/album-id/<?php echo $value['id']; ?>" class="btn  btn-primary">Edit Album</a> | 
                <a href="<?php echo BASE_URL; ?>admin/gallery/delete-album/album-id/<?php echo $value['id']; ?>" class="btn  btn-danger">Delete Album</a> |
                <a href="<?php echo BASE_URL; ?>admin/gallery/list-photos/album-id/<?php echo $value['id']; ?>" class="btn ">List photos</a>
            </td>
            <?php
            $checkval=true;
            $counter ++;
            }
        } 
    ?>
            
    </table>
    
</div>