<?php
$academic = $this->academicInfo;
$post = new Default_Model_Post();
$news = $this->newsSidebar;
$facilities = $this->facilitiesSidebar;
$contact = $this->contact;
?>
<title>Academic</title>
<div class="row-fluid">
    <div id='main_container' class="span12">
        <h1 class="page-head">Academic | Leapfrog College of Engineering</h1>
        <hr>
        <div id="container">
            <h3>LeapFrog Offers following Academic Courses:</h3>

            <table >
                <?php
                if (!empty($academic)):
                    foreach ($academic as $value):
                        $var = explode(" ", $value['post_title']);
                        ?> 
                        <tr>
                            <td><a href="" id="academic-<?php echo $value['id']; ?>" class="<? echo strtolower($var[2]); ?>"><strong>-</strong> <?php echo $value['post_title']; ?></a></td>
                        </tr>
        <?php
    endforeach;
endif;
?>

            </table>


            <div class="content-area" id="b-info">
<?php
if (!empty($academic)):
    foreach ($academic as $value):
        echo $value['post_body'];
    endforeach;
endif;
?>
            </div>
        </div>
        <div class='recent_news_event'>

            <div class="span4">
                <div class="accordion " id="accordion2">
                    <div class="accordion-group">
                        <div class="accordion-heading accordian-head ">
                            <a class="accordion-toggle accordion-style" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                                <h6>Recent News & Events <i class="icon-plus-sign pull-right"></i></h6>
                            </a>
                        </div>
                        <div id="collapseOne" class="accordion-body collapse in">
                            <div class="accordion-inner">
<?php
if (!empty($news)):
    $count = count($news);
    $i = 0;
    foreach ($news as $value):
        ?>
                                        <li>
                                            <a href="<?php echo BASE_URL; ?>news/news-post/id/<?php echo $value['id']; ?>"><?php echo $value['post_title']; ?></a>
                                        <?php
                                        if ($i + 1 === $count):
                                            ?>
                                                <a href="<?php echo BASE_URL; ?>news" class="more-info pull-right">More &raquo;</a>
                                            <?php endif; ?>
                                        </li>
                                            <?php
                                            $i++;
                                        endforeach;
                                    endif;
                                    ?>
                            </div>
                        </div>
                    </div>

                    <div class="accordion-group">
                        <div class="accordion-heading accordian-head">
                            <a class="accordion-toggle event-head" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                                <h6>Our Mission<i class="icon-plus-sign pull-right"></i></h6>
                            </a>
                        </div>
                        <div id="collapseTwo" class="accordion-body collapse">
                            <div class="accordion-inner">

                                <li>A passion for excellence</li>
                                <li>Compassionate commitment </li>
                                <li>Innovative Spirit </li>
                                <li>Ability to accept risks and challenges </li>
                                <li>Competence </li>
                                <li>Creativity  </li>


                            </div>
                        </div>
                    </div>


                    <div class="accordion-group">
                        <div class="accordion-heading accordian-head">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
                                <h6>Facilities <i class="icon-plus-sign pull-right"></i></h6>
                            </a>
                        </div>
                        <div id="collapseThree" class="accordion-body collapse">
                            <div class="accordion-inner">
<?php
if (!empty($facilities)):
    $count = count($facilities);
    $i = 0;
    foreach ($facilities as $value):
        ?>
                                        <li>
                                            <a href="<?php echo BASE_URL; ?>facilities/facility/id/<?php echo $value['id']; ?>" class=""><?php echo $value['post_title']; ?></a>
                                        <?php if ($i + 1 === $count): ?>
                                                <a href='<?php echo BASE_URL; ?>facilities' class='more-info pull-right'>More &raquo;</a>
                                            <?php endif; ?>
                                        </li>
                                            <?php
                                            $i++;
                                        endforeach;
                                    endif;
                                    ?>
                            </div>
                        </div>
                    </div>


                </div>
                <div>
<?php
if (!empty($contact)):
    foreach ($contact as $value):
        ?>
                            <h5><?php echo $value['post_title']; ?></h5>
                            <hr>
                            <div id="contact-info">
        <?php echo $value['post_body']; ?>
                            </div>

                                <?php
                            endforeach;
                        endif;
                        ?>


                </div>
            </div>


        </div>
    </div>
</div>
<script type="text/javascript">
    $(init);

</script>