<?
$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity()) {
    $username = $auth->getIdentity()->user_name;
}
?>

<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>css/style.css"/> 
<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>css/bootstrap.min.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>css/bootstrap-responsive.min.css"/>

<div class="row-fluid">
    <div class="span12">
        <div id="Header">            
            <img src="<?php echo BASE_URL; ?>img/banner.jpg"/>
            <?php
            if ($auth->hasIdentity()):
                ?>
                <div id="log-out">
                    <font>Welcome!!</font><a href="<?php echo BASE_URL . 'admin/user/profile' ?>"><?php echo $username; ?></a>
                    <a href="<?php echo BASE_URL; ?>admin/">Home</a>
                    <a href="<?php echo BASE_URL; ?>admin/index/logout">Log Out</a>
                </div>
            <?php endif; ?>
        </div >
    </div>    
</div>

<div class="row-fluid">
    <div class="span12">
        <div id="main-container">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div id="footer">
            <hr>
            &copy;Leapfrog Technologies
        </div>

    </div>
</div>
<script type="text/javascript" src="<?php echo BASE_URL; ?>js/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>js/common.js"></script>
