<?php
$uri = $_SERVER['REQUEST_URI'];
$pages = explode('/', $uri);
?>
<html>
    <head>

        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>css/bootstrap.min.css"/>
        <link href="<?php echo BASE_URL; ?>css/common.css" rel="stylesheet">

        <script src="<?php echo BASE_URL; ?>js/jquery-1.7.2.min.js"></script>
        <script src="<?php echo BASE_URL; ?>js/bootstrap.min.js"></script>
        <script src="<?php echo BASE_URL; ?>js/common.js"></script>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body>
        <div class="header">
            <div class="logo">
                <a href="<?php echo BASE_URL; ?>" title="home" ><img src="<?php echo BASE_URL; ?>img/logo_1.png"/></a>

            </div>


            <ul>
                <li>
                    <a href="<?php echo BASE_URL; ?>">Home</a>
                </li>
                <li>
                    <a href="<?php echo BASE_URL; ?>about-us" class="<?php echo ($pages[1] == 'about-us') ? 'active' : '' ?>">About Us</a>
                </li>


                <li>
                    <a href="<?php echo BASE_URL; ?>facilities" class="<?php echo ($pages[1] == 'facilities') ? 'active' : '' ?>">Facilities</a>
                </li>

                <li>
                    <a href="<?php echo BASE_URL; ?>academic" class="<?php echo ($pages[1] == 'academic') ? 'active' : '' ?>">Academic</a>
                </li>
                <li>
                    <a href="<?php echo BASE_URL; ?>gallery" class="<?php echo ($pages[1] == 'gallery') ? 'active' : '' ?>">Gallery</a>
                </li>
                <li>
                    <a href="<?php echo BASE_URL; ?>news" class="<?php echo ($pages[1] == 'news') ? 'active' : '' ?>">News & Events</a>
                </li>
                <li>
                    <a href="<?php echo BASE_URL; ?>contact" class="<?php echo ($pages[1] == 'contact') ? 'active' : '' ?>">Contact</a>
                </li>

            </ul>

        </div> 
        <?php echo $this->layout()->content;?>
        
          <!-- footer -->
        <footer>
            <small>&COPY; LEAPFROG COLLEGE OF ENGINEERING</small>
        </footer>

        <!-- close footer-->
    </body>
</html>
